export const refs = {
  gallery: document.querySelector('.film-list'),
  preloader: document.getElementById('spinner'),
  chooseGanresBtn: document.querySelector('.choose-genre-btn'),
  genreContainer: document.querySelector('.genre-container'),
  listGenres: document.querySelector('.list-genre'),
  darkWrapper: document.querySelector('.empty-wrapper-dark'),
  wraperMyLib: document.querySelector('.empty-wrapper'),
  queueBtn: document.querySelector('.secondary'),
  watchedBtn: document.querySelector('.lib-btn.current'),
  btnClearAll: document.querySelector('.btn-clear-all'),
  modal: document.querySelector('.modal'),
  modalOpenBtn: document.querySelector('.footer__btn'),
  closeButton: document.querySelector('.js-modal-team-close'),
  modalFooter: document.querySelector('.modal-team'),
  backdrop: document.querySelector('.overlay-team-modal'),
  body: document.querySelector('body'),
  searchFormEl: document.querySelector('.header__movie-search-form'),
  inputEl: document.querySelector('.movie-search-form'),
  errorEl: document.querySelector('.search-error-message'),
  containerPlagination: document.getElementById('pagination'),
};
