export const refs = {
  gallery: document.querySelector('.film-list'),
  galleryGenre: document.querySelector('.film-list'),
  preloader: document.getElementById('spinner'),
  chooseGanresBtn: document.querySelector('.choose-genre-btn'),
  genreContainer: document.querySelector('.genre-container'),
  listGenres: document.querySelector('.list-genre'),
  noActiveBtn: document.querySelector('.active-btn-genre'),
  darkWrapper: document.querySelector('.empty-wrapper-dark'),
  wraperMyLib: document.querySelector('.empty-wrapper'),
  queueBtn: document.querySelector('.secondary'),
  watchedBtn: document.querySelector('.lib-btn.current'),
  btnClearAll: document.querySelector('.btn-clear-all'),
  mylibWrapper: document.querySelector('.film-list'),
  modal: document.querySelector('.modal'),
};
